// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_cognito_identity_pool_id:
    "us-west-2:b009e503-d6a4-4f29-bb59-295d3972dc81",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_ugwDDfM0F",
  aws_user_pools_web_client_id: "mcgib60hupcqurmh1rk0js5qu",
};

export default awsmobile;
